### ISSUE TITLE
Pagination cache issue

### ISSUE THREAD

**Issue by rad182** [apollographql/apollo-cache-persist#82] opened 2019-01-23 04:15 UTC
Hi, First of all thanks for this awesome library been using this for awhile and it makes my app feels faster.

I'm having issue with pagination caches.
I currently have a feed with inifinite scrolling so basically `feed(first: 5, after: "some end cursor here")`
So when I keep scrolling down then stopped at let say 20 items.
Then I will refresh the browser and apollo will load from cache first and it will show the 20 items instead of the first 5 items. Is this normal?

Problem when i set apollo query fetch policy to `cache-and-network` at first it will show the 20 items then it hits the network and returns back and it will show the 5 items.
Is this the expected result? or is there any workaround for this?
TIA

**Comment by pl12133** [comment] 2019-01-30 16:05
I also have this problem and cannot find a reasonable workaround: https://github.com/apollographql/apollo-client/issues/4068. I can't tell if this is intended behavior or undefined behavior.

**Comment by wtrocki** [comment] 2019-05-13 22:01
This is not normal as variables are taken into consideration when reading from cache. For example when querying with limit 5 there should be query with that specific value saved in cache. 
However if infinite scroll adds to that cache value will be still not accurate as we added more objects. To do it infinite scroll aka update function should swap objects rather than append to overal cache.

**Comment by chengyin** [comment] 2019-06-19 17:29
If I understood correctly, appending through `updateQuery` is exactly what [Apollo's document](https://www.apollographql.com/docs/react/features/pagination/) recommends. Is this not the right way to do pagination with apollo-cache-persist?

**Comment by benjamn** [comment] 2019-06-19 17:39
Assigning to myself, since this is one of the areas we want to improve in the next version of the Apollo Client cache: https://blog.apollographql.com/whats-new-in-apollo-client-2-6-b3acf28ecad1

In short, we're going to make it possible to implement custom reading and writing logic for cache data that can't be handled automatically, such as paginated lists.

**Comment by wtrocki** [comment] 2019-07-25 16:14
@benjamn Is this work going to happen on this repository. Can I help somehow with development/reviews?

**Comment by wtrocki** [comment] 2019-10-25 21:09
Ant update?

**Comment by jspizziri** [comment] 2021-07-29 09:32
Closing this due to inactivity. Please let me know if it needs to be opened back up.

**Closed by jspizziri** 2021-07-29 09:32 UTC
