### ISSUE TITLE
[Question] How to entirely clear client cache?

### ISSUE THREAD

**Issue by beebase** [apollographql/apollo-cache-persist#34] opened 2018-02-15 14:13 UTC
I'd like to completely clear the cache (stored in localStorage) after a user logs out but I can't find anything in the apollo docs.
resetStore() seems to re activate all active queries, effectively restoring the data.

**Comment by n1ru4l** [comment] 2018-02-15 14:25
Check out this section: https://github.com/apollographql/apollo-cache-persist#advanced-usage

**Comment by sce9sc** [comment] 2018-03-06 23:15
I've tried also deleting the local storage using persistor.purge() but it seems that is is never deleted

**Comment by sce9sc** [comment] 2018-03-07 00:52
I've also tried the below steps 
1) persistor.remove();
2) persistor.purge();

and then
3) persistor.persist() 

and the localstorage is populated even though if you query the data is empty

**Comment by n1ru4l** [comment] 2018-03-07 11:17
@sce9sc Can you please create a reproduction scenario using https://codesandbox.io ?

**Comment by jamesreggio** [comment] 2018-03-07 15:33
There are a couple things happening here, so I'm going to share some background that will hopefully help.

* `persistor.purge()` will clear the storage provider (e.g., `localStorage`), but it doesn't clear the in-memory cache, and it doesn't stop persistence from happening again.
* `persistor.remove()` will stop persistence from happening again, but doesn't clear the storage provider or in-memory cache.
* `client.resetStore()` will clear the in-memory cache _and_ refetch all queries, but it has no effect on the persistor.

I regret how convoluted the interaction of these concerns is, and it's something we ought to resolve in Apollo Client 3.0. But, until then, here's the order of events I would advise for a logout:

```js
// User clicks 'log out'.
// First: do whatever is necessary in your app to invalidate/clear out the user's session.
// Then do the following:

persistor.pause(); // Pause automatic persistence.
persistor.purge(); // Delete everything in the storage provider.

// If there are views visible that contain data from the logged-out user,
// this will cause them to clear out. It also issues a bunch of network requests
// for data that likely won't be available anymore since the user is logged-out,
// so you may consider skipping this.
client.resetStore();

// Redirect user to login page.
// At this point, the logged out user may close the tab/app.
// If they do, everything should be good: the storage provider will remain cleared,
// and no prior data will be visible upon next use.

// Let's assume the user logs in.
// First: do whatever is necessary to set the user's session.
// Next: you absolutely must reset the store. This will clear the prior user's data from
// memory and will cause all of the open queries to refetch using the new user's session.
client.resetStore();

// Resume cache persistence. The cache storage provider will be empty right now,
// but it will written with the new user's data the next time the trigger fires.
persistor.resume();
```

Again, I realize how convoluted this is, but login/session management is generally a convoluted thing, because there are hundreds of ways to do it, and it varies quite a bit between native apps vs. single-page apps vs. server-rendered apps.

Perhaps in the future, we could build an Apollo package for managing sessions (and thus Apollo could coordinate all of these actions).

**Comment by sbrichardson** [comment] 2018-03-07 16:32
Thanks for those details

**Comment by jamesreggio** [comment] 2018-03-10 22:22
I'm going to close this issue. If anybody needs further clarification, please don't hesitate to ask.

**Closed by jamesreggio** 2018-03-10 22:22 UTC
Labels: question

**Comment by davidgoli** [comment] 2018-04-12 18:13
@jamesreggio this is good info, it would be great to promote your code to the docs and also give and example of usage in a demo app, because this is an extremely common use case

**Comment by tamlyn** [comment] 2018-10-12 14:41
Note [there is now](https://www.apollographql.com/docs/react/recipes/authentication.html#login-logout) a `client.clearStore()` function which does not refetch queries.

**Comment by techyrajeev** [comment] 2018-12-12 19:50
@jamesreggio I am not sure how to access `persistor` instance from a react component?

**Comment by n1ru4l** [comment] 2018-12-13 10:17
You can either import it in your file directly or use `React.Context` to do so:

```js
// cache-persistor.js
import { createContext } from "react";
import { CachePersistor } from "apollo-cache-persist";

const persistor = new CachePersistor({});
const Context = createContext(persistor);

export const CachePersistor = Context.Consumer;

// your-component.js
import React from "react";
import { CachePersistor } from "./cache-persistor";

export function YourComponent() {
  return (
    <CachePersistor>
      {cachePersistor => (
        <button
          onPress={() => {
            // do sth with cachePersistor here
          }}
        >
          Press me
        </button>
      )}
    </CachePersistor>
  );
}

```

**Comment by noicetoit** [comment] 2019-03-08 15:19
@jamesreggio thank you for the explanation. One question, what if user wants to switch account and wants to login directly after log out? How can I purge the local storage and re-creating it with default client state right when user log out?

**Comment by rewieer** [comment] 2019-07-17 09:19
@jamesreggio i'm falling into the same case as @noicetoit, any advice on this ? As I see the local state is also purged, and the defaults are not set.

**Comment by tm1000** [comment] 2019-07-17 23:41
A solution without using cachePersistor is `client.clearStore()` which was briefly mentioned by @tamlyn above.

**Comment by maltenz** [comment] 2020-05-24 05:36
a combination of 
client.resetStore()
and client.clearStore()
works for me!

**Comment by johnnyoshika** [comment] 2021-01-15 19:34
> a combination of
> client.resetStore()
> and client.clearStore()
> works for me!

@maltenz I don't think it works as you intended. If you reload the browser, the previous cache will be restore from apollo-cache-persist, as it was never purged from there. You need to clear the memory cache (with `client.clearStore()`) AND purge the persistence cache with the example provided by @rewieer.

**Comment by JoaoHamerski** [comment] 2022-02-02 18:17
@jamesreggio solution isn't working anymore, at least on vue-apollo, i simply can't reset the cache when the user logout and login
