### ISSUE TITLE
The cache is restored at the start of the app but a query silently becomes null (only on iOS)

### ISSUE THREAD

**Issue by softhib** [apollographql/apollo-cache-persist#33] opened 2018-02-10 17:44 UTC
Udpate : see directly the next comment.

**Comment by softhib** [comment] 2018-02-11 16:23
Update : I realize that the problem maybe not comes from apollo-cache-persist but from apollo client. Because the problem only happens on iOS and not on Android.

Considering the following snippet : 
```javascript render() {
if (this.props.queryUserLoggedInfos.networkStatus === 1) return null; 
const { userLogged } = this.props.queryUserLoggedInfos;
console.log("=========render userLogged==========");
console.log(userLogged);
console.log("====================================");
```

I got the following result on iOS : 

```javascript 
=========render userLogged==========
{id: "5a2c769d4ef79d57e29c940a", pseudo: "sof", email: "sofiene@torepa.xyz", avatar: "ws5icnrjntmd4bbbvlay", tribu: {…}, …}
====================================
=========render userLogged==========
{id: "5a2c769d4ef79d57e29c940a", pseudo: "sof", email: "sofiene@torepa.xyz", avatar: "ws5icnrjntmd4bbbvlay", tribu: {…}, …}
====================================
remote-redux-devtools: Socket connection errors are being suppressed. 
This can be disabled by setting suppressConnectErrors to 'false'.
SocketProtocolError {name: "SocketProtocolError", message: "Socket hung up", code: 1006, stack: "SocketProtocolError: Socket hung up↵    at SCSocke…a/node_modules/expo/tools/hashAssetFiles:2316:42)"}
=========render userLogged==========
null
====================================
```

So after the first two renders, the cache is filled but at the end of the third it becomes empty. And this problem not appears on Android...

**Comment by n1ru4l** [comment] 2018-02-12 22:35
I can confirm this issue.  If I add a console.log in the render method of my component it will log three times. The first three times are with the actual data object and the last on with `null`.

I am using the following:

```
    "apollo-cache-inmemory": "1.1.7",
    "apollo-cache-persist": "0.1.1",
    "apollo-client": "2.2.3",
    "apollo-link": "1.1.0",
    "apollo-link-context": "1.0.5",
    "apollo-link-error": "1.0.5",
    "apollo-link-http": "1.3.3",
```

**Comment by softhib** [comment] 2018-02-13 09:54
I tried to work around by manually restoring the cache but it results in an infinite loop... 

```javascript
userLoggedCacheRestore = async () => {
    const query = gql`
      query UserLoggedInfos {
        userLogged {
          id
        }
      }
    `;
    const { client } = this.props;
    const result = await AsyncStorage.getItem("apollo-cache-persist");
    const cache = JSON.parse(result);
    console.log(
      "=================cache.ROOT_QUERY.userLogged==================="
    );
    console.log(cache[cache.ROOT_QUERY.userLogged.id]);
    if (cache.ROOT_QUERY.userLogged) {
      client.writeQuery({
        query,
        data: {
          userLogged: cache[cache.ROOT_QUERY.userLogged.id]
        }
      });
    }
  };

render() {
    if (this.props.queryUserLoggedInfos.networkStatus === 1) return null;
    const { userLogged } = this.props.queryUserLoggedInfos;
    if (!userLogged) {
      this.userLoggedCacheRestore();
      return <LoginSignupNavigator />;
    }
```

![capture d ecran 2018-02-13 a 10 46 11 2](https://user-images.githubusercontent.com/31486728/36143468-75602528-10ab-11e8-8195-7388ab11aa5b.png)

**Comment by n1ru4l** [comment] 2018-02-13 10:02
@softhib I do not know if you have the same issue. For me it worked out to first start rendering components that fire queries after the `Promise` returned by `persistCache` resolves.

**Comment by softhib** [comment] 2018-02-13 10:09
@n1ru4l  Ok ! How did you to that ?

**Comment by n1ru4l** [comment] 2018-02-13 11:19
Here is a quick snippet. If you need more details let me know, then I will try to write an expo snack when I got some more time 🤗

```jsx
import React, { Component } from 'react'
import { persistCachePromise, apolloClient } from './apollo-client-setup'
import { ApolloProvider } from 'react-apollo'

// App is your react-native root component
// we delay any app rendering until the store is hydrated
export class App extends Component {
  constructor(...args) {
    super(...args)
    this.state = { isHydratingStore: true }
  }
  componentDidMount() {
    persistCachePromise.then(() => {
      this.setState({ isHydratingStore: false })
    })
  }
  render() {
    if (this.state.isHydratingStore) {
      return null
    }
    return (
      <ApolloProvider client={apolloClient}>
        <YourRealApp />
      </ApolloProvider>
    )
  }
}
```

**Comment by softhib** [comment] 2018-02-13 14:06
Thanks a lot @n1ru4l ! Just a little question : where `persistCachePromise` come from ? Is it a package or something code yourself ?  Because I don't see inside your folder `"./apollo-client-setup"`

**Comment by softhib** [comment] 2018-02-13 14:09
Thanks a lot @n1ru4l ! I have a little question : where persistCachePromise come from ? Is it a package or something code yourself ? Because I don't see inside your folder "./apollo-client-setup"

**Comment by n1ru4l** [comment] 2018-02-13 14:39
Basically the file exports the promise returned by the function `persistCache`

**Comment by softhib** [comment] 2018-02-13 14:47
Ok understood !

**Comment by softhib** [comment] 2018-02-13 15:42
Finally the problem still persists... 😟 I have to investigate.

**Comment by softhib** [comment] 2018-02-13 16:11
I need to know what triggers the third render.

**Comment by softhib** [comment] 2018-02-15 16:33
The issue is probably related to https://github.com/apollographql/apollo-client/issues/2920

**Comment by jamesreggio** [comment] 2018-03-07 15:44
Sorry to hear about the problem, @softhib.

I think you're right about this being a problem in `apollo-client`. I can't say for certain, but I think a network error is causing the third render to be null on iOS.

The fact that `[apollo-cache-persist]` logs about being restored before all of this happens tells me that it's correctly configured. With that being said, @n1ru4l's advice to await the promise returned by `persistCache` is always a good idea — it ensures that the cache has been restored before you start rendering.

I'm going to close this issue for now, but if you find reason to believe that the problem is actually in `apollo-cache-persist`, please feel free to reopen.

**Closed by jamesreggio** 2018-03-07 15:44 UTC

**Comment by agulik** [comment] 2018-07-20 15:24
thank you @n1ru4l your solution worked for me!
