### ISSUE TITLE
 Failed to read the 'localStorage' property from 'Window': Access is denied for this document

### ISSUE THREAD

**Issue by mounikakella** [apollographql/apollo-cache-persist#406] opened 2020-11-25 07:09 UTC
Trying to use apollo-cache-persist in browser incognito mode and it is returning this error.

**Comment by wodCZ** [comment] 2020-11-25 08:42
Hi, this seems to be caused by [this chrome setting](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document).
Probably Chrome's incognito mode has this on by default? (Didn't see this error yet).

As for your options:
- make sure to uncheck `Block third-party cookies and site data`
- wrap cache-persist calls in a `try/catch` to avoid crashes caused by this option
- use different storage provider (`localForage` is supported by this library, that one might work)

**Comment by wtrocki** [comment] 2020-11-25 09:43
Yes. This is where our wrapper framework shine. Users can provide their own wrapper with desired error handling/storage fallback etc.

**Comment by jspizziri** [comment] 2021-09-23 02:25
Closing this issue for now. Let me know if it needs to be reopened.

**Closed by jspizziri** 2021-09-23 02:25 UTC
