### ISSUE TITLE
Overriding my cache specs breaks ability to pull from persisted cache on app launch

### ISSUE THREAD

**Issue by Jonovono** [apollographql/apollo-cache-persist#449] opened 2021-09-22 22:29 UTC
I have basically copied the react native example. Now, when I leave the cache initialized like so then everything works great (on app launch I pull from my persisted cache). However, if I update my cache to be like the following then it doesn't pull from persisted cache and instead makes a network call. Any idea why?

```
import { InMemoryCache } from '@apollo/client'

export const cache: InMemoryCache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        list_by_pk: {
          read(_, { args, toReference }) {
            return toReference({
              __typename: 'list',
              id: args ? args.id : null,
            })
          },
        },
        product: {
          read(_, { args, toReference }) {
            return toReference({
              __typename: 'product',
              id: args ? args.id : null,
            })
          },
        },
        product_by_pk: {
          read(_, { args, toReference }) {
            return toReference({
              __typename: 'product',
              id: args ? args.id : null,
            })
          },
        },
        list: {
          read(_, { args, toReference }) {
            return toReference({
              __typename: 'list',
              id: args ? args.id : null,
            })
          },
        },
      },
    },
  },
})

/**
 * Set initial values when we create cache variables.
 */

```

**Comment by wodCZ** [comment] 2022-07-04 15:24
Closing this as a duplicate of #349.

**Closed by wodCZ** 2022-07-04 15:24 UTC
